# Generated by Django 5.0.2 on 2024-03-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
    ]
